### ISSUE TITLE
consume_queue_timer 函数 时间计算问题

### ISSUE THREAD

**Issue by JackGuoo** [SinaMSRE/Plog#2]
你好，请教Plog代码中Plog/_init_.py中consume_queue_timer函数中

```
    current_time = time.time()
    dealing_time = current_time - current_time % interval

    sleep_time = 1
    while 1:
        current_time = time.time()
        if current_time > dealing_time + interval:
            dealing_time = current_time - current_time % interval
```

这段时间计算的代码与后面while中时间比较的代码为什么要这么写呢？

另外如果interval是一个较大的数字

```
    if current_time > dealing_time + interval:
            dealing_time = current_time - current_time % interval
            sink_controller.deal_sink()
        else:
            if dict_queue.qsize() > 0:
                dict_item = dict_queue.get()
                sink_controller.calculate_item(item=dict_item)
```

会多次执行else中的dict_queue.get() 但是并没有执行sink_controller.deal_sink()
这样是不是丢失了中间的sink_controller.calculate_item(item=dict_item)的结果？

**Comment by lurenx** [comment]
首先我们会在整点(x分00秒)去 consume queue 去做计算。

程序第一次启动，运行到这里的时候

如果现在的unix time 是 1467965050(2016/7/8 16:4:10) ,所以我们的初始化的时间 current_time 也就是 1467965050,所以我们的初始化 dealing_time也就是1467965000。

定时器不断的计时，while 1 不断的去check，然后某一个时刻，也就是 current_time > dealing_time + interval(在dealing_time的基础上过了一个interval，也就是处理的周期)的时候， 我们可以去 consume queue,这个时候，也要修改下dealing_time,计时器继续计时

其实  

```
      if current_time > dealing_time + interval:
            dealing_time = current_time - current_time % interval
```

同样可以写作

```
        if current_time > dealing_time + interval:
            dealing_time += interval
```

**Comment by openpy** [comment]
循环中如果没有到处理周期并且队列里面有数据那么sink_controller.calculate_item(item=dict_item)就会进行处理，但是并没有调用sink_controller.deal_sink()这样会不会丢失item，并且sink_controller.calculate_item(item=dict_item)函数处理的数据暂存在哪里呢？

**Comment by JackGuoo** [comment]
while中在一个处理周期内多次执行sink_controller.calculate_item(item=dict_item)而没有执行sink_controller.deal_sink()这样会不会会导致数据丢失，为什么不执行完sink_controller.calculate_item(item=dict_item)后直接执行sink_controller.deal_sink()
谢谢

**Comment by lurenx** [comment]
因为sink_controller.deal_sink()的处理时间就是一个周期。所以他只能一个周期跑一次。而数据计算为什么一个周期跑多次，因为我们希望内存中只有很少的且简单的kv，所以一个周期计算多次，减轻内存占用。另外，这个数据用在监控这个简单的业务层面，即使数据丢失，也没多大影响，所以，当时就忽略了数据丢失的场景。

**Comment by aszhou** [comment]
您好，请问该项目是否还在维护？后面还有计划没有？ 因为我们现在系统目前体量比较小，暂时用不上Flume。

**Comment by lurenx** [comment]
当然在维护。看上面的提问，工作日我一般会很及时的回复，休息日会有延迟。 由于，当时我们的初衷需求很简单，所以实现了功能并且没有新的需求了，所以代码一直没有更新。
